# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "zimbres/github"
          source_branch: "main"
          destination_repo: "git@ssh.dev.azure.com:v3/zimbresdotcom/GitHub/GitHub"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
